upstream karing_backend {
    server karing:8080;
}

upstream karing_web_frontend {
    server karing-web:8080;
}

server {
    listen 80;
    server_name karing.example.com;

    location = /web {
        return 301 /web/;
    }

    location /web/ {
        proxy_pass http://karing_web_frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://karing_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
